### ISSUE TITLE
Folder structuur moet gesorteerd blijven.

### ISSUE THREAD

**Issue by jvdwijk** [jvdwijk/Proeve#32]
[Audio Mixer](https://github.com/jvdwijk/Proeve/blob/development/Assets/Music%20Mixer.mixer) moet niet in de base map van de Asset folder.
Er mogen geen scripts in de basis folder van Scripts/

**Comment by JustinvanGemen** [comment]
Folder structuur geupdate zodat alles in de correcte folders zit.
